services:
  - type: web
    name: student-health-assistant-backend
    runtime: python
    region: ohio  # Choose the region closest to your users
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn health_project.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: health_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: student-health-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        sync: false  # You'll set this manually to include your frontend URL
      - key: STATIC_ROOT
        value: staticfiles

databases:
  - name: student-health-db
    region: ohio
    plan: free
